### ISSUE TITLE
"required" property not checked?

### ISSUE THREAD

**Issue by alyjak** [acao/codemirror-json-schema#75]
Looking through https://github.com/acao/codemirror-json-schema/blob/main/src/__tests__/json-validation.spec.ts I don't see a test to ensure that required properties within an object are checked for. Moreover, in my application, I'm not seeing any lint errors when I include an object in my json that are missing required properties per my linked schema.

Is this expected behavior? If not, I'm not sure if this repo, https://www.npmjs.com/package/json-schema-library, or https://www.npmjs.com/package/@types/json-schema is the root of the issue.

**Comment by acao** [comment]
It is not expected behavior. Required properties work in some cases but not all. We still have so many specs to confirm!

to note, `@types/json-schema` is a type library. the library that takes care of validation logic is `json-schema-library`, so we may need to report a bug to them

**Comment by SilverDY** [comment]
I am facing the same problem.

```json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://example.com/product.schema.json",
    "properties": {
        "ex": {
            "type": "number"
        },
        "in": {
            "type": "number"
        }
    },
    "required": [
        "ex",
        "in"
    ],
    "additionalProperties": false
}
```

`required` doesn't work in any case.

**Comment by acao** [comment]
Ok, I will report the bug to the library once I am recovered

**Comment by acao** [comment]
Ok so I took a break from covid to check this out, and you're correct, it is indeed a bug with how we are generating the pointers from `json-schema-library`, and thus it is something we should test for!

I hope to have a patch fix released before the weekend

**Comment by acao** [comment]
asking my collaborator @imolorhe  - do you agree that we should be including each array item in the parsed pointer map? this way, we can target specific array items for errors like these?
![image](https://github.com/acao/codemirror-json-schema/assets/1368727/c1d06f83-c3b0-482d-9d01-bd71bd6ae512)

**Comment by imolorhe** [comment]
> do you agree that we should be including each array item in the parsed pointer map? this way, we can target specific array items for errors like these?

Yeah this sounds good to me!

**Comment by acao** [comment]
@alyjak @SilverDY 0.5.1 is the fix release! sorry for the delay

**Comment by SilverDY** [comment]
@acao thank you so much for that!
