### ISSUE TITLE
YAML support

### ISSUE THREAD

**Issue by ankrgyl** [acao/codemirror-json-schema#84]
Have you considered adding support for YAML?

**Comment by ankrgyl** [comment]
There is now! https://github.com/codemirror/lang-yaml

**Comment by imolorhe** [comment]
FYI I've picked this up. Will see how easy it is to add a yaml mode.

**Comment by imolorhe** [comment]
[Done](https://github.com/acao/codemirror-json-schema/pull/85)!
[Demo](https://deploy-preview-85--codemirror-json-schema.netlify.app/)
