### ISSUE TITLE
Missing License 

### ISSUE THREAD

**Issue by emilyrohrbough** [acao/codemirror-json-schema#90]
Please add a license to your project! ❤️ 🙌🏻 

https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository

I see you have MIT in your [package.json](https://github.com/acao/codemirror-json-schema/blob/main/package.json#L3), however the license is missing from the repo.

**Comment by acao** [comment]
@emilyrohrbough I'm happy to say that the `LICENSE` file is published to npm as of 0.7.1 🥳 
https://unpkg.com/browse/codemirror-json-schema@0.7.1/LICENSE

**Comment by acao** [comment]
the only remaining bug here appears to be that @imolorhe left himself out of the copyright when adding the file, despite creating more than half of this project 😆
