### ISSUE TITLE
Error validation

### ISSUE THREAD

**Issue by rookie-luochao** [acao/codemirror-json-schema#98]
<img width="729" alt="image" src="https://github.com/acao/codemirror-json-schema/assets/22948077/0bab4686-939d-4ed7-97e6-2c10c1985f31">

expected object, the actual value is 123, but no verification error is prompted

**Comment by imolorhe** [comment]
@acao any reason you don't want to provide validation when there's no pointer? https://github.com/acao/codemirror-json-schema/blob/main/src/json-validation.ts#L139

In this case we wouldn't have a matching pointer so we don't show the error (Note: we can append the root `#` pointer but the effect will be the same as just using `pushRoot()`)

**Comment by rookie-luochao** [comment]
I think this behavior is a bug, monaco-editor will prompt this behavior, because I tend to replace monaco-editor because it is too big to implement json-editor
